baseURL = 'https://indentedblock.com/'
title = 'Indented Block'
theme = 'PaperMod'
paginate = 10

[services.googleAnalytics]
  ID = 'G-15MX54NJ4E'

[params]
  description = "Practical patterns for working developers"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowShareButtons = false
  ShowRssButtonInSectionTermList = true
  ShowToc = true
  TocOpen = false

[[params.socialIcons]]
  name = "rss"
  url = "/index.xml"

[taxonomies]
  tag = "tags"
  series = "series"

[[menus.main]]
  name = "About"
  url = "/about/"
  weight = 5

[[menus.main]]
  name = "Contact"
  url = "/contact/"
  weight = 6

[[menus.main]]
  name = "Tags"
  url = "/tags/"
  weight = 10
